//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WorldSOAPClient.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCountryByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCityByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCitiesByCountryCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WorldSOAPClient.Properties.Settings.Default.WorldSOAPClient_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAllCitiesCompletedEventHandler getAllCitiesCompleted;
        
        /// <remarks/>
        public event getAllCountriesCompletedEventHandler getAllCountriesCompleted;
        
        /// <remarks/>
        public event getCountryByCodeCompletedEventHandler getCountryByCodeCompleted;
        
        /// <remarks/>
        public event getCityByNameCompletedEventHandler getCityByNameCompleted;
        
        /// <remarks/>
        public event getCitiesByCountryCodeCompletedEventHandler getCitiesByCountryCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllCities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City[] getAllCities() {
            object[] results = this.Invoke("getAllCities", new object[0]);
            return ((City[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllCitiesAsync() {
            this.getAllCitiesAsync(null);
        }
        
        /// <remarks/>
        public void getAllCitiesAsync(object userState) {
            if ((this.getAllCitiesOperationCompleted == null)) {
                this.getAllCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllCitiesOperationCompleted);
            }
            this.InvokeAsync("getAllCities", new object[0], this.getAllCitiesOperationCompleted, userState);
        }
        
        private void OngetAllCitiesOperationCompleted(object arg) {
            if ((this.getAllCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllCitiesCompleted(this, new getAllCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllCountries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Country[] getAllCountries() {
            object[] results = this.Invoke("getAllCountries", new object[0]);
            return ((Country[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllCountriesAsync() {
            this.getAllCountriesAsync(null);
        }
        
        /// <remarks/>
        public void getAllCountriesAsync(object userState) {
            if ((this.getAllCountriesOperationCompleted == null)) {
                this.getAllCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllCountriesOperationCompleted);
            }
            this.InvokeAsync("getAllCountries", new object[0], this.getAllCountriesOperationCompleted, userState);
        }
        
        private void OngetAllCountriesOperationCompleted(object arg) {
            if ((this.getAllCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllCountriesCompleted(this, new getAllCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCountryByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Country getCountryByCode(string code) {
            object[] results = this.Invoke("getCountryByCode", new object[] {
                        code});
            return ((Country)(results[0]));
        }
        
        /// <remarks/>
        public void getCountryByCodeAsync(string code) {
            this.getCountryByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void getCountryByCodeAsync(string code, object userState) {
            if ((this.getCountryByCodeOperationCompleted == null)) {
                this.getCountryByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCountryByCodeOperationCompleted);
            }
            this.InvokeAsync("getCountryByCode", new object[] {
                        code}, this.getCountryByCodeOperationCompleted, userState);
        }
        
        private void OngetCountryByCodeOperationCompleted(object arg) {
            if ((this.getCountryByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCountryByCodeCompleted(this, new getCountryByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCityByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City[] getCityByName(string name) {
            object[] results = this.Invoke("getCityByName", new object[] {
                        name});
            return ((City[])(results[0]));
        }
        
        /// <remarks/>
        public void getCityByNameAsync(string name) {
            this.getCityByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void getCityByNameAsync(string name, object userState) {
            if ((this.getCityByNameOperationCompleted == null)) {
                this.getCityByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCityByNameOperationCompleted);
            }
            this.InvokeAsync("getCityByName", new object[] {
                        name}, this.getCityByNameOperationCompleted, userState);
        }
        
        private void OngetCityByNameOperationCompleted(object arg) {
            if ((this.getCityByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCityByNameCompleted(this, new getCityByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCitiesByCountryCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City[] getCitiesByCountryCode(string name) {
            object[] results = this.Invoke("getCitiesByCountryCode", new object[] {
                        name});
            return ((City[])(results[0]));
        }
        
        /// <remarks/>
        public void getCitiesByCountryCodeAsync(string name) {
            this.getCitiesByCountryCodeAsync(name, null);
        }
        
        /// <remarks/>
        public void getCitiesByCountryCodeAsync(string name, object userState) {
            if ((this.getCitiesByCountryCodeOperationCompleted == null)) {
                this.getCitiesByCountryCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCitiesByCountryCodeOperationCompleted);
            }
            this.InvokeAsync("getCitiesByCountryCode", new object[] {
                        name}, this.getCitiesByCountryCodeOperationCompleted, userState);
        }
        
        private void OngetCitiesByCountryCodeOperationCompleted(object arg) {
            if ((this.getCitiesByCountryCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCitiesByCountryCodeCompleted(this, new getCitiesByCountryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class City {
        
        private int idField;
        
        private string nameField;
        
        private string countryCodeField;
        
        private string districtField;
        
        private int populationField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public int Population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Country {
        
        private string codeField;
        
        private string nameField;
        
        private string continentField;
        
        private string regionField;
        
        private decimal surfaceAreaField;
        
        private System.Nullable<short> indepYearField;
        
        private int populationField;
        
        private System.Nullable<decimal> lifeExpectancyField;
        
        private System.Nullable<decimal> gNPField;
        
        private System.Nullable<decimal> gNPOldField;
        
        private string localNameField;
        
        private string governmentFormField;
        
        private string headOfStateField;
        
        private System.Nullable<int> capitalField;
        
        private string code2Field;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Continent {
            get {
                return this.continentField;
            }
            set {
                this.continentField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public decimal SurfaceArea {
            get {
                return this.surfaceAreaField;
            }
            set {
                this.surfaceAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> IndepYear {
            get {
                return this.indepYearField;
            }
            set {
                this.indepYearField = value;
            }
        }
        
        /// <remarks/>
        public int Population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LifeExpectancy {
            get {
                return this.lifeExpectancyField;
            }
            set {
                this.lifeExpectancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GNP {
            get {
                return this.gNPField;
            }
            set {
                this.gNPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> GNPOld {
            get {
                return this.gNPOldField;
            }
            set {
                this.gNPOldField = value;
            }
        }
        
        /// <remarks/>
        public string LocalName {
            get {
                return this.localNameField;
            }
            set {
                this.localNameField = value;
            }
        }
        
        /// <remarks/>
        public string GovernmentForm {
            get {
                return this.governmentFormField;
            }
            set {
                this.governmentFormField = value;
            }
        }
        
        /// <remarks/>
        public string HeadOfState {
            get {
                return this.headOfStateField;
            }
            set {
                this.headOfStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
            }
        }
        
        /// <remarks/>
        public string Code2 {
            get {
                return this.code2Field;
            }
            set {
                this.code2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getAllCitiesCompletedEventHandler(object sender, getAllCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getAllCountriesCompletedEventHandler(object sender, getAllCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getCountryByCodeCompletedEventHandler(object sender, getCountryByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCountryByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCountryByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getCityByNameCompletedEventHandler(object sender, getCityByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCityByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCityByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getCitiesByCountryCodeCompletedEventHandler(object sender, getCitiesByCountryCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCitiesByCountryCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCitiesByCountryCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591